### ISSUE TITLE
org-variable-pitch - How to use the default face as fixed face?

### ISSUE THREAD

**Issue by ThibautVerron** [cadadr/elisp#51]
Hi,

The fixed face is set by the variable `org-variable-pitch-fixed-font` (family only) and the face `org-variable-pitch-face` (everything else). The family part cannot be set in the face because it is rewritten when the mode is loaded.

What is the easiest way to get ovp to use the default face for fixed space?

At the moment I have something like

```
(setq org-variable-pitch-fixed-font
  (face-attribute 'default :family))
 
(require 'org-variable-pitch)

(set-face-attribute 'org-variable-pitch-face nil
  :inherit 'default)
```
  
but it seems to cause me to lose, for example, the highlighting of source block headers.

Is there a better way to do it?

And is there a good reason why ovp, by default, uses a different font than the default monospace font?

**Comment by cadadr** [comment]
The main reason we have that variable is that people might customise `default` _after_ loading OVP, so if it just inherited from `default`, it could still differ from it. Also, some people may use a non-monospaced font for `default`.

But I think that the way it behaves here is not good indeed, so I'll try to come up with something better.

In the mean time I think removing line 134

      (set-face-attribute 'org-variable-pitch-face nil :family org-variable-pitch-fixed-font)

and then in your init.el

    (set-face-attribute 'org-variable-pitch-face (face-attribute 'default :font))

could improve your situation. If you try it, can you report if it works fine and helps with your situation afterwards?

Guess obsoleting `org-variable-pitch-fixed-font`, adding an `org-variable-pitch-setup` function that syncs `org-variable-pitch-face` with `default`, and documenting how it behaves could be an improvement. Ideally I'd wish to have `org-variable-pitch-face` inherit from `default` directly, but it seems that it's not possible to inherit only part of a face's attributes, which results in the issue you have with highlights.

FWIW, this is kinda rooted in my own config, because all monospace fonts are governed by a single variable somewhere in my init.el and this issue seems to be that thing leaking into ovp.el. Sorry for the inconvenience.

**Comment by cadadr** [comment]
Actually, would you mind giving [this](https://github.com/cadadr/elisp/blob/ovp-new-face-setup/org-variable-pitch.el) a try? I've set up a branch to test out a possible enhancement for this situation. If it's not clear what to do from reading the docs for [`org-variable-pitch-setup`](https://github.com/cadadr/elisp/blob/ovp-new-face-setup/org-variable-pitch.el#L168) in there, tell me here and I'll elaborate on what happens in this new version.

**Comment by ThibautVerron** [comment]
Hey, thanks for the replies and the quick fix.

I had a look at the docstrings, it looks pretty intuitive and overall a reasonable solution. I will try it at work on Monday but I don't expect any surprise.

Thanks again!

>  Also, some people may use a non-monospaced font for default.

That's a good point. `fixed-pitch` would be a better choice, but we would have to check if it does the right thing for users who have only set up `default` and possibly `variable-pitch`.

**Comment by cadadr** [comment]
Thank you, and you're welcome!

TIL that `fixed-pitch` exists... Maybe we introduce some logic that checks if `default` is monospace (using maybe `custom-face-state` and sth else to determine font pitch, IDK what that could be, maybe `font-info`) and use `fixed-pitch` if it's not. There's the "spc" attribute in the X font spec strings (XLFDs, I guess), but I gotta do some searching later if it's reliable.

**Comment by ThibautVerron** [comment]
Hi, after testing the new branch, it looks fine. Thanks again!

It looks like `fixed-pitch` by default does not inherit from default, or vice-versa. In theory, I would say that it should be fine to use `fixed-pitch` as basis and advise users who have set only `default` (me included) to set `fixed-pitch` it to their liking. 

Intuitively, I think that a proper setup, instead of just setting `default`, is to set `fixed-pitch` and/or `variable-pitch`, and then have `default` inherit from one of those. I just changed my config for that, and it seems to work, but faces in Emacs are frequently more complicated than they look.

Fwiw, I don't think trying to automatically detect whether `default` is fixed pitch or not is worth it. If you want to support both cases, wouldn't a customizable variable, with a proper setter, be enough? Just adding a couple recognized symbol values to `org-variable-pitch-fixed-font`, for example?

**Comment by cadadr** [comment]
On 2020-08-03 11:37 +03, ThibautVerron <notifications@github.com> wrote:
> Hi, after testing the new branch, it looks fine. Thanks again!

You’re welcome! Sorry it took so long to get back to you.

> It looks like `fixed-pitch` by default does not inherit from default, or vice-versa. In theory, I would say that it should be fine to use `fixed-pitch` as basis and advise users who have set only `default` (me included) to set `fixed-pitch` it to their liking.
>
> Intuitively, I think that a proper setup, instead of just setting `default`, is to set `fixed-pitch` and/or `variable-pitch`, and then have `default` inherit from one of those. I just changed my config for that, and it seems to work, but faces in Emacs are frequently more complicated than they look.

I just tried getting this to work a bit but it seems like it’s not
supposed to work because ‘default’ is apparently not meant to inherit
from anything. "(elisp) Face Attributes" says:

      Apart from the values given below, each face attribute can have
   the value ‘unspecified’.  This special value means that the face
   doesn’t specify that attribute directly.  An ‘unspecified’ attribute
   tells Emacs to refer instead to a parent face (see the description
   ‘:inherit’ attribute below); or, failing that, to an underlying face
   (*note Displaying Faces::).  The ‘default’ face must specify all
   attributes.

I’ve tried to get default to inherit from fixed-pitch in vain and it
seems to me that it only works when system default monospace coincides
with the :family of default, as an accident.  I’m not sure of the
inverse but it again seems to me that plain :inherit from default in
fixed-pitch does not seem to bind their :family together.

In any case I’m pushing a new patch to the branch. Could you just give
it a test to see if it breaks anything or not? This only syncs :family
between the faces so zoom in and out doesn’t break, and it uses the
value of org-variable-pitch-fixed-font only if it appears to be changed,
in order to not break old style setups.

I tried to :inherit directly from default or fixed-pitch but it means
_all_ values of those faces have priority and thus discoloured TODO
tags, tables, &c.

> Fwiw, I don't think trying to automatically detect whether `default` is fixed pitch or not is worth it. If you want to support both cases, wouldn't a customizable variable, with a proper setter, be enough? Just adding a couple recognized symbol values to `org-variable-pitch-fixed-font`, for example?

I think now that I’d ideally just support one and not complicate
stuff. It appears to me that as it is now, I could just get values from
default face for the default setup, and those who want to use an
alternate value could just use the alternative setup documented in
org-variable-pitch-setup’s docstring. This way it’d be backwards
compatible, require no setup for those who want to just use whatever
default looks like, and modifications to ovp fixed-face are
respected. What do you think?

Either way, if this doesn’t break yor setup and there’s nothing to fix,
I think I’ll then just ask folks on /r/emacs to see if this breaks
anything, and if not just merge the branch into the release one.

Cheers,

        -gk


--
İ. Göktuğ Kayaalp / @cadadr / <https://www.gkayaalp.com/>
pgp:   024C 30DD 597D 142B 49AC 40EB 465C D949 B101 2427

**Comment by ThibautVerron** [comment]
> I’ve tried to get default to inherit from fixed-pitch in vain and it
seems to me that it only works when system default monospace coincides
with the :family of default, as an accident. 

I'm not sure of that. After noticing the discrepancy the other time I changed my settings from setting `default` to setting `fixed-pitch` and using inherit for default, and I didn't have any problem:

```
(set-face-attribute 'fixed-pitch nil :font "Inconsolata" :height 120)
(set-face-attribute 'default nil :inherit 'fixed-pitch)
```

Result of describe-face: 

```
Face: default (sample) (customize this face)

Documentation:
Basic default face.

Defined in `faces.el'.

        Family: Inconsolata
       Foundry: PfEd
         Width: normal
        Height: 120
        Weight: normal
         Slant: normal
    Foreground: #000000
    Background: white
     Underline: nil
      Overline: nil
Strike-through: nil
           Box: nil
       Inverse: nil
       Stipple: nil
          Font: #<font-object -PfEd-Inconsolata-normal-normal-normal-*-16-*-*-*-m-0-iso10646-1>
       Fontset: -PfEd-Inconsolata-normal-normal-normal-*-16-*-*-*-m-0-fontset-auto1
       Inherit: fixed-pitch
```

My system-wide monospace font is not Inconsolata, probably DejaVu Sans Mono (my DE calling it "Monospace" doesn't help)...

> I’m not sure of the
inverse but it again seems to me that plain :inherit from default in
fixed-pitch does not seem to bind their :family together.

Or do you mean that you expect that changing `fixed-pitch` after setting the inheritance should propagate to `default`? If so, then yes it does not seem to happen, instead it looks like all the properties are statically copied.

I'm not sure if it is a big problem, those fonts should be set early and not touched afterwards. 

> In any case I’m pushing a new patch to the branch. Could you just give
it a test to see if it breaks anything or not? This only syncs :family
between the faces so zoom in and out doesn’t break, and it uses the
value of org-variable-pitch-fixed-font only if it appears to be changed,
in order to not break old style setups.

I never thought of testing zooming with the old version, but it does not appear to work with the new version either.
If I don't call the setup function, `org-variable-pitch-fixed-face` is DejaVu Sans Mono and zooming works correctly (but the size is wrong even at the default zoom level.

If I do call the setup function, only the family is set, as expected:

```
Face: org-variable-pitch-fixed-face (sample) (customize this face)

Documentation:
Face for initial space and list item bullets.
This face is used to keep them in monospace when using
‘org-variable-pitch-minor-mode’.

Defined in `org-variable-pitch.el'.

        Family: Inconsolata
       Foundry: unspecified
         Width: unspecified
        Height: unspecified
        Weight: unspecified
         Slant: unspecified
    Foreground: unspecified
    Background: unspecified
     Underline: unspecified
      Overline: unspecified
Strike-through: unspecified
           Box: unspecified
       Inverse: unspecified
       Stipple: unspecified
          Font: unspecified
       Fontset: unspecified
       Inherit: unspecified

```

But zooming does not appear to change the monospace font size.

> I think now that I’d ideally just support one and not complicate
stuff. It appears to me that as it is now, I could just get values from
default face for the default setup, and those who want to use an
alternate value could just use the alternative setup documented in
org-variable-pitch-setup’s docstring. This way it’d be backwards
compatible, require no setup for those who want to just use whatever
default looks like, and modifications to ovp fixed-face are
respected. What do you think?

Yes that sounds good.

> Either way, if this doesn’t break yor setup and there’s nothing to fix,
I think I’ll then just ask folks on /r/emacs to see if this breaks
anything, and if not just merge the branch into the release one.

That also sounds like a good idea regardless. Fonts are tricky and there are too many ways of setting them.

Cheers, thanks for your work!
Thibaut
